export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const FETCH_PROFILE_START = 'FETCH_PROFILE_START';
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS';
export const FETCH_PROFILE_FAIL = 'FETCH_PROFILE_FAIL';

export const EDIT_PROFILE_START = 'EDIT_PROFILE_START';
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';

export const ADD_PROFILE_START = 'ADD_PROFILE_START';
export const ADD_PROFILE_FAIL = 'ADD_PROFILE_FAIL';
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS';

export const FETCH_AVAILABILITIES_START = 'FETCH_AVAILABILITIES_START';
export const FETCH_AVAILABILITIES_SUCCESS = 'FETCH_AVAILABILITIES_SUCCESS';
export const FETCH_AVAILABILITIES_FAIL = 'FETCH_AVAILABILITIES_FAIL';

export const ADD_AVAILABILITIES_START = 'ADD_AVAILABILITIES_START';
export const ADD_AVAILABILITIES_SUCCESS = 'ADD_AVAILABILITIES_SUCCESS';
export const ADD_AVAILABILITIES_FAIL = 'ADD_AVAILABILITIES_FAIL';

export const FETCH_WORKING_TIME_START = 'FETCH_WORKING_TIME_START';
export const FETCH_WORKING_TIME_SUCCESS = 'FETCH_WORKING_TIME_SUCCESS';
export const FETCH_WORKING_TIME_FAIL = 'FETCH_WORKING_TIME_FAIL';

export const ADD_WORKING_TIME_START = 'ADD_WORKING_TIME_START';
export const ADD_WORKING_TIME_SUCCESS = 'ADD_WORKING_TIME_SUCCESS';
export const ADD_WORKING_TIME_FAIL = 'ADD_WORKING_TIME_FAIL';

export const UPDATE_SERVICE_EMPLOYEEID = 'UPDATE_SERVICE_EMPLOYEEID';
export const ADD_SERVICES_START = 'ADD_SERVICES_START';
export const ADD_SERVICES_SUCCESS = 'ADD_SERVICES_SUCCESS';
export const ADD_SERVICES_FAIL = 'ADD_SERVICES_FAIL';
export const REMOVE_SERVICES_START = 'REMOVE_SERVICES_START';
export const REMOVE_SERVICES_SUCCESS = 'REMOVE_SERVICES_SUCCESS';
export const REMOVE_SERVICES_FAIL = 'REMOVE_SERVICES_FAIL';

export const ADD_BOOKING_START = 'ADD_BOOKING_START';
export const ADD_BOOKING_SUCCESS = 'ADD_BOOKING_SUCCESS';
export const ADD_BOOKING_FAIL = 'ADD_BOOKING_FAIL';

export const UPDATE_REDIRECT = 'UPDATE_REDIRECT';
export const RESET_REDIRECT = 'RESET_REDIRECT';

export const FETCH_EMPLOYEE_START = 'FETCH_EMPLOYEE_START';
export const FETCH_EMPLOYEE_SUCCESS = 'FETCH_EMPLOYEE_SUCCESS';
export const FETCH_EMPLOYEE_FAIL = 'FETCH_EMPLOYEE_FAIL';
